[auth]
username = "mekatronik"
password = "a12b34"

[firebase]
type                        = "service_account"
project_id                  = "YOUR_PROJECT_ID"
private_key_id              = "YOUR_PRIVATE_KEY_ID"
private_key                 = "-----BEGIN PRIVATE KEY-----\nYOUR_KEY\n-----END PRIVATE KEY-----\n"
client_email                = "YOUR_CLIENT_EMAIL"
client_id                   = "YOUR_CLIENT_ID"
auth_uri                    = "https://accounts.google.com/o/oauth2/auth"
token_uri                   = "https://oauth2.googleapis.com/token"
databaseURL                 = "https://YOUR_PROJECT.firebaseio.com"
```
